Package ‘JuliaCall’
October 25, 2018
Type Package
Title Seamless Integration Between R and 'Julia'
Version 0.16.1
Date 2018-10-24

#### Description
 Provides an R interface to 'Julia',
which is a high-level, high-performance dynamic programming language
for numerical computing, see <https://julialang.org/> for more information.
It provides a high-level interface as well as a low-level interface.
Using the high level interface, you could call any 'Julia' function just like
any R function with automatic type conversion. Using the low level interface,
you could deal with C-level SEXP directly while enjoying the convenience of
using a high-level programming language like 'Julia'.
Depends R (>= 3.4.0)
License MIT + file LICENSE
URL https://github.com/Non-Contradiction/JuliaCall
BugReports https://github.com/Non-Contradiction/JuliaCall/issues
Encoding UTF-8
LazyData true
Imports utils, Rcpp (>= 0.12.7)
RoxygenNote 6.1.0
LinkingTo Rcpp
NeedsCompilation yes
ByteCompile yes
SystemRequirements Julia >= 0.6.0, RCall.jl
Suggests testthat, knitr, rmarkdown
VignetteBuilder knitr
Author Changcheng Li [aut, cre],
Randy Lai [ctb],
Dmitri Grominski [ctb],
Nagi Teramo [ctb]
1
2 autowrap
Maintainer Changcheng Li <cxl508@psu.edu>
Repository CRAN
Date/Publication 2018-10-25 20:00:03 UTC
R topics documented:
autowrap . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 2
call . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 3
eng_juliacall . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 4
JuliaCall . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 4
JuliaObject . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 5
JuliaObjectFields . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 6
julia_assign . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 7
julia_command . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 7
julia_console . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 8
julia_eval . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 8
julia_exists . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 9
julia_help . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 9
julia_package . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 10
julia_setup . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 11
julia_source . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 12
plotsViewer . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 12
%>J% . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 12
Index 14

